### ISSUE TITLE
Proposal for combinatorial barcoding

### ISSUE THREAD

**Issue by kdm9** [najoshi/sabre#3]
Hi Nik,

We're moving to the use of combinatorial barcoding to allow multiplexing more than 96 samples per lane. This involves different R1 & R2 barcodes (e.g. 12 R1 barcodes \* 8 R2 barcodes  = 96 unique barcode combinations).

While sabre can trim barcodes from both pairs, from what I can tell from the code it does no matching on the R2 read.

Therefore I propose (and am happy to implement myself, assuming it will be merged) the following:
- A new command, `sabre comb`, to handle this use case.
- A new barcode file format to handle this:

| R1 Barcode | R2 Barcode | R1 Output File | R2 Output File |
| --- | --- | --- | --- |
| AAACTG | TGATG | ./first_barcode_R1.fq | ./first_barcode_R2.fq |
| TAACTG | ACATG | ./2nd_barcode_R1.fq | ./2nd_barcode_R2.fq |

....

Cheers,
Kevin

**Comment by kdm9** [comment]
Implementing this turned out to be way easier than expected. This looks like it works, with the test files I used it perfectly assigned them to their respective places.

The work in progress is [here](https://github.com/kdmurray91/sabre/compare/comb).
I'll submit a pull request when I'm done.

**Comment by timyerg** [comment]
Hi @kdm9!
I am apologizing for writing in the old thread, but is there any chance I can install your modification of Sabre?
In my experience it works better (thanks developers!) than cutadapt but now I have dual barcodes and Sabre do not recognize added reverse barcodes. I tried to install it from your fork but it also did not work.

**Comment by kdm9** [comment]
@timyerg wow this is a blast from the past. I actually subsequently wrote an entire tool with a new algorithm called [axe](https://github.com/kdm9/axe) which I recommend you use instead

**Comment by timyerg** [comment]
@kdm9 Thank you for a quick reply ! I will try axe instead, hope it will work better than cutadapt, which always creates several too large samples with reads from other samples (even with no mismatches in settings).
